FROM ubuntu:latest
MAINTAINER Messias Batista <mrafaelbatista@gmail.com>

#Atualização do sistema
RUN apt-get update && apt-get upgrade -y

#Criação de diretório
RUN mkdir /database

#Diretório de trabalho
WORKDIR /database

#Instalação de aplicações
RUN apt-get install vim -y

#Baixando o Oracle Database Express 11g
ADD 


#Porta exposta para comunicação
EXPOSE 80