FROM php:7-fpm
MAINTAINER Messias Batista <mrafaelbatista@gmail.com>

#Atualização do sistema
RUN apt-get update && apt-get upgrade -y

#Instalação do editor Vim
RUN apt-get install vim -y

#Instalação da Internet
RUN apt-get install -y php-apc    
RUN apt-get install -y libxml2-dev 
RUN apt-get install -y libldb-dev
RUN apt-get install -y libldap2-dev 
RUN apt-get install -y libxml2-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y libxslt-dev
RUN apt-get install -y libpq-dev
RUN apt-get install -y postgresql-client
RUN apt-get install -y mysql-client 
RUN apt-get install -y libsqlite3-dev
RUN apt-get install -y libsqlite3-0
RUN apt-get install -y libc-client-dev
RUN apt-get install -y libkrb5-dev
RUN apt-get install -y curl
RUN apt-get install -y libcurl3
RUN apt-get install -y libcurl3-dev
RUN apt-get install -y firebird-dev
RUN apt-get install -y libpspell-dev
RUN apt-get install -y aspell-en
RUN apt-get install -y aspell-pt-br
RUN apt-get install -y aspell-es
RUN apt-get install -y libtidy-dev
RUN apt-get install -y libsnmp-dev
RUN apt-get install -y librecode0
RUN apt-get install -y librecode-dev

#Instalações de extensões do php internet
RUN docker-php-ext-install soap
RUN docker-php-ext-install ftp
RUN docker-php-ext-install xsl
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install calendar
RUN docker-php-ext-install ctype
RUN docker-php-ext-install dba
RUN docker-php-ext-install dom
RUN docker-php-ext-install zip
RUN docker-php-ext-install session
RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu
RUN docker-php-ext-install ldap
RUN docker-php-ext-install json
RUN docker-php-ext-install hash
RUN docker-php-ext-install sockets
RUN docker-php-ext-install pdo
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install tokenizer
RUN docker-php-ext-install pgsql
RUN docker-php-ext-install pdo_pgsql
RUN docker-php-ext-install pdo_mysql 
RUN docker-php-ext-install pdo_sqlite
RUN docker-php-ext-install intl
RUN docker-php-ext-install mcrypt
RUN docker-php-ext-install mysqli
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl
RUN docker-php-ext-install imap
RUN docker-php-ext-install gd
RUN docker-php-ext-install curl
RUN docker-php-ext-install exif
RUN docker-php-ext-install fileinfo
RUN docker-php-ext-install gettext
RUN apt-get install -y libgmp-dev 
RUN docker-php-ext-install gmp 
RUN docker-php-ext-install iconv
RUN docker-php-ext-install interbase
RUN docker-php-ext-install pdo_firebird
RUN docker-php-ext-install opcache
RUN docker-php-ext-install oci8 
RUN docker-php-ext-install odbc 
RUN docker-php-ext-install pcntl
RUN apt-get install -y freetds-dev 
RUN docker-php-ext-install pdo_dblib  
RUN docker-php-ext-install pdo_oci 
RUN docker-php-ext-install pdo_odbc 
RUN docker-php-ext-install phar
RUN docker-php-ext-install posix
RUN docker-php-ext-install pspell
RUN apt-get install -y libreadline-dev 
RUN docker-php-ext-install readline
RUN docker-php-ext-install recode
RUN docker-php-ext-install shmop
RUN docker-php-ext-install simplexml
RUN docker-php-ext-install snmp
RUN docker-php-ext-install sysvmsg
RUN docker-php-ext-install sysvsem
RUN docker-php-ext-install sysvshm
RUN docker-php-ext-install tidy
RUN docker-php-ext-install wddx
RUN docker-php-ext-install xml
RUN apt-get install -y libxml2-dev 
RUN docker-php-ext-install xmlreader 
RUN docker-php-ext-install xmlrpc
RUN docker-php-ext-install xmlwriter 

#Instalação extensões do php
RUN docker-php-ext-install pdo pdo_mysql pdo_dblib pdo_oci pdo_pgsql pdo_sqlsrv
RUN docker-php-ext-install pgsql mysql sqlsrv mongodb 
RUN  docker-php-ext-install xdebug mcrypt 

#Criação de diretório
RUN mkdir /code

#Diretório de trabalho
WORKDIR /code