version: '2'
services:
    web:
        #image: nginx:latest
        image: mrafaelbatista/nginx:v0.1
        ports:
            - "8080:80"
        volumes:
            - "./www:/code"
            # Apenas se precisar alterar a config do NGINX
            #- "./site.conf:/etc/nginx/conf.d/default.conf"
        depends_on:
            - php
        links:
            - php
        restart: always
    
    php:
        #image: php:7-fpm
        image: mrafaelbatista/php7-fpm:v0.1
        volumes:
            - "./www:/code"
        restart: always